version: "3"

services:
  mongo:
    image: mongo
    env_file: .env
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
      - 27018:27018
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - mongo-compose-network

  mongo-express:
    image: mongo-express
    env_file: .env
    container_name: mongo-express
    restart: always
    ports:
      - 8888:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - mongo-compose-network

  backend:
    env_file: .env
    environment:
      MONGODB_HOST: mongo
      MONGODB_USER: user
      MONGODB_PASS: password
      MONGODB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGODB_PORT: 27017
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/usr/src/app/src
      - ./static:/user/app/static
    ports:
      - "5000:5000"
      - "3000:3000"
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge
