version: "3"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
  mysql:
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest-api-database
      TZ: "Asia/Tokyo"
    ports:
      - 3308:3306
  minio:
    image: "minio/minio"
    ports:
      - "9000:9000"
    # volumes:
    #   - os:/data
    command: server /data
    environment:
      MINIO_ACCESS_KEY: mimamori
      MINIO_SECRET_KEY: mimamori
