version: "3"

services:
  metabase:
    container_name: metabase
    image: metabase/metabase
    ports:
      - 3001:3000
    networks:
      - mysql-network
    environment:
      VIRTUAL_HOST: ${METABASE_DOMAIN_NAME}
      VIRTUAL_PORT: 3001
      LETSENCRYPT_HOST: ${METABASE_DOMAIN_NAME}
      LETSENCRYPT_EMAIL: ${EMAIL}
      SSL_POLICY: "Mozilla-Modern"
  mysql:
    image: mysql:5
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest-api-database
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    networks:
      - mysql-network
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    environment:
      MONGODB_HOST: ${MONGODB_HOST}
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASS: ${MONGODB_PASS}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
      MONGODB_PORT: 27017
      MYSQL_HOST: mysql
      MYSQL_DATABASE: nest-api-database
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
      VIRTUAL_HOST: ${WEB_DOMAIN_NAME}
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: ${WEB_DOMAIN_NAME}
      LETSENCRYPT_EMAIL: ${EMAIL}
      SSL_POLICY: "Mozilla-Modern"
    networks:
      - mysql-network
      # - nginx_proxy_link
    ports:
      - 3000:3000
      - 5000:5000
      - 4000:4000

networks:
  mysql-network:
    driver: bridge
  # nginx_proxy_link:
  #   external: true
