name: push & PR event

on:
  pull_request:
    branches-ignore:
      - master
  push:
    branches-ignore:
      - master

jobs:
  client:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [10.x]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@preview
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ matrix.os }}-node-
      - name: Install Dependencies
        run: yarn install
      - name: Lint
        run: yarn lint:client
      - name: Build
        run: yarn client:build:prod

  backend:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [10.x]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@preview
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ matrix.os }}-node-
      - name: Install Dependencies
        run: yarn install
      - name: Lint
        run: yarn lint:server
      - name: Build
        run: yarn server:build:prod
