name: push & PR event

on:
  pull_request:
    branches:
      - "*/*"
      - "*"
      - "!master"
  push:
    branches:
      - "*/*"
      - "*"
      - "!master"

jobs:
  backend:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [10.x]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@preview
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Install Dependencies
        run: yarn install
      # - name: run test
      #   run: yarn test
      - name: run lint
        run: yarn lint
      - name: build
        run: yarn build
      - uses: actions/upload-artifact@master
        with:
          name: backend dist directory
          path: dist
